# Generated by Django 6.0.5 on 2026-06-07 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('posicoes', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado')], max_length=20, verbose_name='status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='accounts.usuario', verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'inventário',
                'verbose_name_plural': 'inventários',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_fisica', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='quantidade física')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inventario.inventario', verbose_name='inventário')),
                ('posicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_inventario', to='posicoes.posicao', verbose_name='posição')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_inventario', to='produtos.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'item de inventário',
                'verbose_name_plural': 'itens de inventário',
                'ordering': ['inventario', 'produto'],
            },
        ),
    ]
