# Generated by Django 6.0.5 on 2026-06-07 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('posicoes', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCiclico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_sap', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='quantidade SAP')),
                ('ultima_contagem', models.DateTimeField(blank=True, null=True, verbose_name='última contagem')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONTADO', 'Contado'), ('DIVERGENTE', 'Divergente')], default='PENDENTE', max_length=20, verbose_name='status')),
            ],
            options={
                'verbose_name': 'item cíclico',
                'verbose_name_plural': 'itens cíclicos',
                'ordering': ['plano', 'produto__codigo_produto'],
            },
        ),
        migrations.CreateModel(
            name='PlanoCiclico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('produtos', 'Produtos por dia'), ('posicoes', 'Posições por dia')], max_length=20, verbose_name='tipo')),
                ('quantidade_por_dia', models.PositiveIntegerField(verbose_name='quantidade por dia')),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='data de geração')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'plano cíclico',
                'verbose_name_plural': 'planos cíclicos',
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='confronto_executado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='confronto executado em'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='status_aprovacao',
            field=models.CharField(blank=True, choices=[('PENDENTE_APROVACAO', 'Pendente de Aprovação'), ('APROVADO', 'Aprovado')], max_length=30, verbose_name='status de aprovação'),
        ),
        migrations.AddConstraint(
            model_name='inventarioitem',
            constraint=models.UniqueConstraint(fields=('inventario', 'posicao', 'produto'), name='uniq_inventarioitem_inventario_posicao_produto'),
        ),
        migrations.AddField(
            model_name='itemciclico',
            name='posicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_ciclicos', to='posicoes.posicao', verbose_name='posição'),
        ),
        migrations.AddField(
            model_name='itemciclico',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_ciclicos', to='produtos.produto', verbose_name='produto'),
        ),
        migrations.AddField(
            model_name='itemciclico',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inventario.planociclico', verbose_name='plano'),
        ),
        migrations.AddConstraint(
            model_name='itemciclico',
            constraint=models.UniqueConstraint(fields=('plano', 'produto', 'posicao'), name='uniq_itemciclico_plano_produto_posicao'),
        ),
    ]
