# Generated by Django 6.0.5 on 2026-06-09 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_itemciclico_planociclico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='data_contagem',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data da contagem'),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='origem_contagem',
            field=models.CharField(blank=True, choices=[('POCKET', 'Pocket'), ('WEB', 'Web')], max_length=10, verbose_name='origem da contagem'),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='usuario_contagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_inventario_contados', to=settings.AUTH_USER_MODEL, verbose_name='usuário da contagem'),
        ),
    ]
