# Generated by Django 6.0.5 on 2026-06-09 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rastreabilidade_contagem'),
        ('posicoes', '0001_initial'),
        ('produtos', '0002_embalagem_remove_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloAuditoriaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONTAGEM', 'Contagem'), ('RECONTAGEM', 'Recontagem')], max_length=20, verbose_name='tipo')),
                ('data_hora', models.DateTimeField(verbose_name='data e hora')),
                ('quantidade_sap_momento', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='quantidade SAP no momento')),
                ('quantidade_fisica', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='quantidade física')),
                ('diferenca', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='diferença')),
            ],
            options={
                'verbose_name': 'histórico de auditoria cíclica',
                'verbose_name_plural': 'históricos de auditoria cíclica',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='CicloInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_encerramento', models.DateTimeField(blank=True, null=True, verbose_name='data de encerramento')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'ciclo de inventário cíclico',
                'verbose_name_plural': 'ciclos de inventário cíclico',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='CicloInventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=50, verbose_name='código do produto')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('embalagem', models.CharField(blank=True, max_length=100, verbose_name='embalagem')),
                ('codigo_posicao', models.CharField(max_length=50, verbose_name='código da posição')),
                ('alocacao', models.CharField(blank=True, max_length=100, verbose_name='alocação')),
                ('setor', models.CharField(blank=True, max_length=100, verbose_name='setor')),
                ('quantidade_sap', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='quantidade SAP')),
                ('quantidade_fisica', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='quantidade física')),
                ('diferenca', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='diferença')),
                ('data_contagem', models.DateTimeField(blank=True, null=True, verbose_name='data da contagem')),
                ('data_atualizacao_sap', models.DateTimeField(blank=True, null=True, verbose_name='data de atualização SAP')),
                ('status_contagem', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONTADO', 'Contado'), ('DIVERGENTE', 'Divergente'), ('RECONTAGEM', 'Recontagem'), ('VALIDADO', 'Validado')], default='PENDENTE', max_length=20, verbose_name='status da contagem')),
                ('data_recontagem', models.DateTimeField(blank=True, null=True, verbose_name='data da recontagem')),
                ('quantidade_recontagem', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='quantidade da recontagem')),
            ],
            options={
                'verbose_name': 'item do ciclo cíclico',
                'verbose_name_plural': 'itens do ciclo cíclico',
                'ordering': ['ciclo', 'codigo_produto', 'codigo_posicao'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='itemciclico',
            name='uniq_itemciclico_plano_produto_posicao',
        ),
        migrations.AddField(
            model_name='cicloauditoriahistorico',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_ciclo_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='cicloinventario',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclos_inventario_criados', to=settings.AUTH_USER_MODEL, verbose_name='usuário de criação'),
        ),
        migrations.AddField(
            model_name='cicloinventarioitem',
            name='ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inventario.cicloinventario', verbose_name='ciclo'),
        ),
        migrations.AddField(
            model_name='cicloinventarioitem',
            name='posicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_ciclo_inventario', to='posicoes.posicao', verbose_name='posição'),
        ),
        migrations.AddField(
            model_name='cicloinventarioitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_ciclo_inventario', to='produtos.produto', verbose_name='produto'),
        ),
        migrations.AddField(
            model_name='cicloinventarioitem',
            name='usuario_contagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_ciclo_contados', to=settings.AUTH_USER_MODEL, verbose_name='usuário da contagem'),
        ),
        migrations.AddField(
            model_name='cicloinventarioitem',
            name='usuario_recontagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_ciclo_recontados', to=settings.AUTH_USER_MODEL, verbose_name='usuário da recontagem'),
        ),
        migrations.AddField(
            model_name='cicloauditoriahistorico',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='inventario.cicloinventarioitem', verbose_name='item do ciclo'),
        ),
        migrations.RemoveField(
            model_name='itemciclico',
            name='plano',
        ),
        migrations.RemoveField(
            model_name='itemciclico',
            name='posicao',
        ),
        migrations.RemoveField(
            model_name='itemciclico',
            name='produto',
        ),
        migrations.AddConstraint(
            model_name='cicloinventarioitem',
            constraint=models.UniqueConstraint(fields=('ciclo', 'produto', 'posicao'), name='uniq_cicloitem_ciclo_produto_posicao'),
        ),
        migrations.DeleteModel(
            name='PlanoCiclico',
        ),
        migrations.DeleteModel(
            name='ItemCiclico',
        ),
    ]
