# Generated by Django 6.0.5 on 2026-06-09 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_ciclo_auditoria_restructure'),
        ('produtos', '0002_embalagem_remove_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cicloinventarioitem',
            options={'ordering': ['ciclo', 'codigo_produto', 'codigo_posicao'], 'verbose_name': 'posição do ciclo cíclico', 'verbose_name_plural': 'posições do ciclo cíclico'},
        ),
        migrations.AddField(
            model_name='cicloauditoriahistorico',
            name='codigo_posicao',
            field=models.CharField(blank=True, max_length=50, verbose_name='código da posição'),
        ),
        migrations.AddField(
            model_name='cicloinventario',
            name='quantidade_skus_planejados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade de SKUs planejados'),
        ),
        migrations.AlterField(
            model_name='cicloauditoriahistorico',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='inventario.cicloinventarioitem', verbose_name='posição do ciclo'),
        ),
        migrations.AlterField(
            model_name='cicloauditoriahistorico',
            name='tipo',
            field=models.CharField(choices=[('CONTAGEM', 'Contagem'), ('RECONTAGEM', 'Recontagem'), ('CONSOLIDACAO', 'Consolidação')], max_length=20, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='CicloInventarioSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=50, verbose_name='código do produto')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('embalagem', models.CharField(blank=True, max_length=100, verbose_name='embalagem')),
                ('setor', models.CharField(blank=True, max_length=100, verbose_name='setor')),
                ('quantidade_sap', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='quantidade SAP')),
                ('quantidade_fisica', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='quantidade física consolidada')),
                ('diferenca', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='diferença')),
                ('data_atualizacao_sap', models.DateTimeField(blank=True, null=True, verbose_name='data de atualização SAP')),
                ('status_contagem', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONTADO', 'Contado'), ('DIVERGENTE', 'Divergente'), ('RECONTAGEM', 'Recontagem'), ('VALIDADO', 'Validado')], default='PENDENTE', max_length=20, verbose_name='status da contagem')),
                ('data_recontagem', models.DateTimeField(blank=True, null=True, verbose_name='data da recontagem')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='inventario.cicloinventario', verbose_name='ciclo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus_ciclo_inventario', to='produtos.produto', verbose_name='produto')),
                ('usuario_recontagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skus_ciclo_recontados', to=settings.AUTH_USER_MODEL, verbose_name='usuário da recontagem')),
            ],
            options={
                'verbose_name': 'SKU do ciclo cíclico',
                'verbose_name_plural': 'SKUs do ciclo cíclico',
                'ordering': ['ciclo', 'codigo_produto'],
            },
        ),
        migrations.AddField(
            model_name='cicloauditoriahistorico',
            name='ciclo_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='inventario.cicloinventariosku', verbose_name='SKU do ciclo'),
        ),
        migrations.AddField(
            model_name='cicloinventarioitem',
            name='ciclo_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='inventario.cicloinventariosku', verbose_name='SKU do ciclo'),
        ),
        migrations.AddConstraint(
            model_name='cicloinventariosku',
            constraint=models.UniqueConstraint(fields=('ciclo', 'produto'), name='uniq_ciclosku_ciclo_produto'),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _migrar_itens_para_sku(apps),
            reverse_code=migrations.RunPython.noop,
        ),
    ]


def _migrar_itens_para_sku(apps):
    CicloInventario = apps.get_model('inventario', 'CicloInventario')
    CicloInventarioItem = apps.get_model('inventario', 'CicloInventarioItem')
    CicloInventarioSku = apps.get_model('inventario', 'CicloInventarioSku')
    CicloAuditoriaHistorico = apps.get_model('inventario', 'CicloAuditoriaHistorico')

    for ciclo in CicloInventario.objects.all():
        produto_ids = (
            CicloInventarioItem.objects.filter(ciclo=ciclo)
            .values_list('produto_id', flat=True)
            .distinct()
        )
        ciclo.quantidade_skus_planejados = len(produto_ids)
        ciclo.save(update_fields=['quantidade_skus_planejados'])

        for produto_id in produto_ids:
            itens = CicloInventarioItem.objects.filter(ciclo=ciclo, produto_id=produto_id)
            primeiro = itens.first()
            if primeiro is None:
                continue

            sap_total = sum(item.quantidade_sap for item in itens)
            fisico_total = sum(
                item.quantidade_recontagem or item.quantidade_fisica or 0
                for item in itens
                if item.quantidade_fisica is not None or item.quantidade_recontagem is not None
            )
            status = primeiro.status_contagem
            status_counts = {item.status_contagem for item in itens}
            if any(valor != 'PENDENTE' for valor in status_counts):
                status = next(
                    valor for valor in status_counts if valor != 'PENDENTE'
                )

            sku = CicloInventarioSku.objects.create(
                ciclo=ciclo,
                produto_id=produto_id,
                codigo_produto=primeiro.codigo_produto,
                descricao=primeiro.descricao,
                embalagem=primeiro.embalagem,
                setor=primeiro.setor,
                quantidade_sap=sap_total,
                quantidade_fisica=fisico_total or None,
                diferenca=(fisico_total - sap_total) if fisico_total else None,
                data_atualizacao_sap=primeiro.data_atualizacao_sap,
                status_contagem=status,
                usuario_recontagem_id=primeiro.usuario_recontagem_id,
                data_recontagem=primeiro.data_recontagem,
            )
            itens.update(ciclo_sku=sku)
            CicloAuditoriaHistorico.objects.filter(item__in=itens).update(ciclo_sku=sku)
