# Generated by Django 6.0.5 on 2026-06-09

from django.db import migrations, models


def preencher_ordem_planejamento(apps, schema_editor):
    CicloInventarioSku = apps.get_model('inventario', 'CicloInventarioSku')
    for ciclo_id in (
        CicloInventarioSku.objects.values_list('ciclo_id', flat=True).distinct()
    ):
        skus = CicloInventarioSku.objects.filter(ciclo_id=ciclo_id).order_by(
            'codigo_produto',
            'pk',
        )
        for ordem, sku in enumerate(skus, start=1):
            if sku.ordem_planejamento != ordem:
                sku.ordem_planejamento = ordem
                sku.save(update_fields=['ordem_planejamento'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_ciclo_orientado_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicloinventario',
            name='dia_execucao',
            field=models.PositiveIntegerField(
                default=1,
                verbose_name='dia de execução atual',
            ),
        ),
        migrations.AddField(
            model_name='cicloinventario',
            name='skus_por_dia',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name='SKUs por dia na execução',
            ),
        ),
        migrations.AddField(
            model_name='cicloinventariosku',
            name='ordem_planejamento',
            field=models.PositiveIntegerField(
                default=0,
                verbose_name='ordem no planejamento',
            ),
        ),
        migrations.RunPython(
            preencher_ordem_planejamento,
            migrations.RunPython.noop,
        ),
    ]
