# Generated by Django 6.0.5 on 2026-06-10 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_ciclo_usuario_encerramento'),
        ('posicoes', '0001_initial'),
        ('produtos', '0003_produto_participa_ciclico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloEstoqueFisicoAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=50, verbose_name='código do produto')),
                ('codigo_posicao', models.CharField(max_length=50, verbose_name='código da posição')),
                ('quantidade_anterior', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='quantidade anterior')),
                ('quantidade_nova', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='quantidade nova')),
                ('diferenca', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='diferença')),
                ('data_hora', models.DateTimeField(verbose_name='data e hora')),
                ('origem', models.CharField(choices=[('INVENTARIO_CICLICO', 'Inventário cíclico')], default='INVENTARIO_CICLICO', max_length=30, verbose_name='origem')),
                ('motivo', models.TextField(blank=True, verbose_name='motivo')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_estoque_fisico', to='inventario.cicloinventario', verbose_name='ciclo')),
                ('ciclo_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_estoque_fisico', to='inventario.cicloinventariosku', verbose_name='SKU do ciclo')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_estoque_fisico', to='inventario.cicloinventarioitem', verbose_name='posição auditada')),
                ('posicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_ciclico_estoque_fisico', to='posicoes.posicao', verbose_name='posição')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_ciclico_estoque_fisico', to='produtos.produto', verbose_name='produto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_ciclico_estoque_fisico', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'ajuste de estoque físico (cíclico)',
                'verbose_name_plural': 'ajustes de estoque físico (cíclico)',
                'ordering': ['-data_hora'],
            },
        ),
    ]
