# Generated by Django 6.0.5 on 2026-06-10 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_ciclo_estoque_fisico_ajuste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cicloestoquefisicoajuste',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_estoque_fisico', to='inventario.cicloinventarioitem', verbose_name='posição auditada'),
        ),
    ]
