# Generated by Django 6.0.5 on 2026-06-12 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_sincronizar_status_itens_validados'),
        ('posicoes', '0002_posicao_apto_posicao_data_precadastro_posicao_nivel_and_more'),
        ('produtos', '0004_produto_data_precadastro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cicloinventarioitem',
            name='status_contagem',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_CONTAGEM', 'Em Contagem'), ('CONTADO', 'Contado'), ('DIVERGENTE', 'Divergente'), ('RECONTAGEM', 'Em Recontagem'), ('APROVADA', 'Aprovada'), ('FINALIZADA', 'Finalizada'), ('VALIDADO', 'Validado')], default='PENDENTE', max_length=20, verbose_name='status da contagem'),
        ),
        migrations.CreateModel(
            name='InventarioTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inventario', models.CharField(choices=[('GERAL', 'Inventário Geral'), ('CICLICO', 'Inventário Cíclico')], max_length=10, verbose_name='tipo de inventário')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_CONTAGEM', 'Em Contagem'), ('CONTADA', 'Contada'), ('DIVERGENTE', 'Divergente'), ('EM_RECONTAGEM', 'Em Recontagem'), ('APROVADA', 'Aprovada'), ('FINALIZADA', 'Finalizada')], default='PENDENTE', max_length=20, verbose_name='status')),
                ('modo_atribuicao', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICA', 'Automática'), ('HIBRIDA', 'Híbrida')], default='AUTOMATICA', max_length=15, verbose_name='modo de atribuição')),
                ('area_criterio', models.JSONField(blank=True, default=dict, verbose_name='critério de área')),
                ('atribuido_em', models.DateTimeField(auto_now_add=True, verbose_name='atribuído em')),
                ('iniciado_em', models.DateTimeField(blank=True, null=True, verbose_name='iniciado em')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='finalizado em')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('eh_recontagem', models.BooleanField(default=False, verbose_name='é recontagem')),
                ('operadores_anteriores', models.JSONField(blank=True, default=list, verbose_name='operadores anteriores')),
                ('atribuido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='atribuído por')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='inventario.cicloinventario', verbose_name='ciclo')),
                ('ciclo_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='inventario.cicloinventarioitem', verbose_name='item cíclico')),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='inventario.inventario', verbose_name='inventário')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_inventario', to=settings.AUTH_USER_MODEL, verbose_name='operador')),
                ('posicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_inventario', to='posicoes.posicao', verbose_name='posição')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_inventario', to='produtos.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'tarefa de inventário',
                'verbose_name_plural': 'tarefas de inventário',
                'ordering': ['ordem', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='InventarioLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inventario', models.CharField(choices=[('GERAL', 'Inventário Geral'), ('CICLICO', 'Inventário Cíclico')], max_length=10, verbose_name='tipo de inventário')),
                ('dispositivo', models.CharField(blank=True, max_length=200, verbose_name='dispositivo')),
                ('session_key', models.CharField(blank=True, max_length=64, verbose_name='chave de sessão')),
                ('adquirido_em', models.DateTimeField(verbose_name='adquirido em')),
                ('renovado_em', models.DateTimeField(verbose_name='renovado em')),
                ('expira_em', models.DateTimeField(verbose_name='expira em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('liberado_em', models.DateTimeField(blank=True, null=True, verbose_name='liberado em')),
                ('motivo_liberacao', models.CharField(blank=True, choices=[('MANUAL', 'Liberação manual'), ('TIMEOUT', 'Timeout automático'), ('CONCLUIDO', 'Contagem concluída'), ('SESSAO', 'Encerramento de sessão'), ('ADMIN', 'Liberação administrativa')], max_length=20, verbose_name='motivo da liberação')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='inventario.cicloinventario', verbose_name='ciclo')),
                ('ciclo_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='inventario.cicloinventarioitem', verbose_name='item cíclico')),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='inventario.inventario', verbose_name='inventário')),
                ('posicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locks_inventario', to='posicoes.posicao', verbose_name='posição')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locks_inventario', to='produtos.produto', verbose_name='produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locks_inventario', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locks', to='inventario.inventariotarefa', verbose_name='tarefa')),
            ],
            options={
                'verbose_name': 'lock de inventário',
                'verbose_name_plural': 'locks de inventário',
                'ordering': ['-adquirido_em'],
            },
        ),
        migrations.CreateModel(
            name='InventarioAuditoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inventario', models.CharField(choices=[('GERAL', 'Inventário Geral'), ('CICLICO', 'Inventário Cíclico')], max_length=10, verbose_name='tipo de inventário')),
                ('evento', models.CharField(choices=[('LOCK_ADQUIRIDO', 'Lock adquirido'), ('LOCK_RENOVADO', 'Lock renovado'), ('LOCK_LIBERADO', 'Lock liberado'), ('LOCK_TIMEOUT', 'Lock expirado (timeout)'), ('TAREFA_ATRIBUIDA', 'Tarefa atribuída'), ('TAREFA_INICIADA', 'Tarefa iniciada'), ('TAREFA_FINALIZADA', 'Tarefa finalizada'), ('CONTAGEM', 'Contagem registrada'), ('STATUS_ALTERADO', 'Status alterado'), ('RECONTAGEM_GERADA', 'Recontagem gerada'), ('DIVERGENCIA', 'Divergência detectada')], max_length=25, verbose_name='evento')),
                ('dispositivo', models.CharField(blank=True, max_length=200, verbose_name='dispositivo')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('lote', models.CharField(blank=True, max_length=100, verbose_name='lote')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='quantidade')),
                ('status_anterior', models.CharField(blank=True, max_length=30, verbose_name='status anterior')),
                ('status_novo', models.CharField(blank=True, max_length=30, verbose_name='status novo')),
                ('dados_extras', models.JSONField(blank=True, default=dict, verbose_name='dados extras')),
                ('data_hora', models.DateTimeField(verbose_name='data e hora')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_auditoria', to='inventario.cicloinventario', verbose_name='ciclo')),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_auditoria', to='inventario.inventario', verbose_name='inventário')),
                ('posicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria_inventario', to='posicoes.posicao', verbose_name='posição')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria_inventario', to='produtos.produto', verbose_name='produto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria_inventario', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('lock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to='inventario.inventariolock', verbose_name='lock')),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to='inventario.inventariotarefa', verbose_name='tarefa')),
            ],
            options={
                'verbose_name': 'evento de auditoria operacional',
                'verbose_name_plural': 'eventos de auditoria operacional',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='inventariotarefa',
            index=models.Index(fields=['tipo_inventario', 'inventario', 'operador', 'status'], name='idx_tarefa_geral_op'),
        ),
        migrations.AddIndex(
            model_name='inventariotarefa',
            index=models.Index(fields=['tipo_inventario', 'ciclo', 'operador', 'status'], name='idx_tarefa_ciclico_op'),
        ),
        migrations.AddIndex(
            model_name='inventariotarefa',
            index=models.Index(fields=['status'], name='idx_tarefa_status'),
        ),
        migrations.AddIndex(
            model_name='inventariolock',
            index=models.Index(fields=['ativo', 'expira_em'], name='idx_lock_ativo_expira'),
        ),
        migrations.AddIndex(
            model_name='inventariolock',
            index=models.Index(fields=['tipo_inventario', 'inventario', 'posicao', 'ativo'], name='idx_lock_geral_pos'),
        ),
        migrations.AddIndex(
            model_name='inventariolock',
            index=models.Index(fields=['tipo_inventario', 'ciclo', 'posicao', 'ativo'], name='idx_lock_ciclico_pos'),
        ),
        migrations.AddIndex(
            model_name='inventariolock',
            index=models.Index(fields=['usuario', 'ativo'], name='idx_lock_usuario_ativo'),
        ),
        migrations.AddConstraint(
            model_name='inventariolock',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('tipo_inventario', 'GERAL')), fields=('tipo_inventario', 'inventario', 'posicao', 'produto'), name='uniq_lock_geral_pos_prod_ativo'),
        ),
        migrations.AddConstraint(
            model_name='inventariolock',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('tipo_inventario', 'CICLICO')), fields=('tipo_inventario', 'ciclo', 'posicao', 'produto'), name='uniq_lock_ciclico_pos_prod_ativo'),
        ),
        migrations.AddIndex(
            model_name='inventarioauditoriaevento',
            index=models.Index(fields=['tipo_inventario', 'inventario', 'data_hora'], name='inventario__tipo_in_a75751_idx'),
        ),
        migrations.AddIndex(
            model_name='inventarioauditoriaevento',
            index=models.Index(fields=['tipo_inventario', 'ciclo', 'data_hora'], name='inventario__tipo_in_5ddb42_idx'),
        ),
        migrations.AddIndex(
            model_name='inventarioauditoriaevento',
            index=models.Index(fields=['evento', 'data_hora'], name='inventario__evento_8e896f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventarioauditoriaevento',
            index=models.Index(fields=['usuario', 'data_hora'], name='inventario__usuario_3a8f9f_idx'),
        ),
    ]
