# Generated by Django 6.0.5 on 2026-06-14 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_multiusuario_locks_tarefas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioauditoriaevento',
            name='evento',
            field=models.CharField(choices=[('LOCK_ADQUIRIDO', 'Lock adquirido'), ('LOCK_RENOVADO', 'Lock renovado'), ('LOCK_LIBERADO', 'Lock liberado'), ('LOCK_TIMEOUT', 'Lock expirado (timeout)'), ('TAREFA_ATRIBUIDA', 'Tarefa atribuída'), ('TAREFA_INICIADA', 'Tarefa iniciada'), ('TAREFA_FINALIZADA', 'Tarefa finalizada'), ('CONTAGEM', 'Contagem registrada'), ('CONTAGEM_REJEITADA', 'Contagem rejeitada'), ('STATUS_ALTERADO', 'Status alterado'), ('RECONTAGEM_GERADA', 'Recontagem gerada'), ('DIVERGENCIA', 'Divergência detectada')], max_length=25, verbose_name='evento'),
        ),
        migrations.CreateModel(
            name='CicloLoteExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='data de geração')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('SUBSTITUIDO', 'Substituído'), ('ENCERRADO', 'Encerrado')], default='ATIVO', max_length=20, verbose_name='status')),
                ('quantidade_solicitada', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade solicitada')),
                ('embalagens', models.JSONField(blank=True, default=list, verbose_name='embalagens')),
                ('canal', models.CharField(blank=True, max_length=100, verbose_name='canal')),
                ('respeitar_somente_embalagens', models.BooleanField(default=False, verbose_name='respeitar somente embalagens')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_execucao', to='inventario.cicloinventario', verbose_name='ciclo')),
                ('usuario_geracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_ciclico_gerados', to=settings.AUTH_USER_MODEL, verbose_name='usuário de geração')),
            ],
            options={
                'verbose_name': 'lote de execução cíclica',
                'verbose_name_plural': 'lotes de execução cíclica',
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.CreateModel(
            name='CicloLoteExecucaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.PositiveIntegerField(verbose_name='sequência')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONTADO', 'Contado'), ('EXCLUIDO', 'Excluído')], default='PENDENTE', max_length=20, verbose_name='status')),
                ('ciclo_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_execucao_itens', to='inventario.cicloinventariosku', verbose_name='SKU do ciclo')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inventario.cicloloteexecucao', verbose_name='lote')),
            ],
            options={
                'verbose_name': 'item do lote cíclico',
                'verbose_name_plural': 'itens do lote cíclico',
                'ordering': ['sequencia'],
            },
        ),
        migrations.AddIndex(
            model_name='cicloloteexecucao',
            index=models.Index(fields=['ciclo', 'status', '-data_geracao'], name='idx_ciclo_lote_ativo'),
        ),
        migrations.AddConstraint(
            model_name='cicloloteexecucaoitem',
            constraint=models.UniqueConstraint(fields=('lote', 'ciclo_sku'), name='uniq_ciclo_lote_item_sku'),
        ),
    ]
