# Generated by Django 6.0.5 on 2026-06-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_inventario_snapshot_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cicloauditoriahistorico',
            name='dispositivo_contagem',
            field=models.CharField(blank=True, max_length=200, verbose_name='dispositivo da contagem'),
        ),
        migrations.AlterField(
            model_name='cicloinventarioitem',
            name='dispositivo_contagem',
            field=models.CharField(blank=True, max_length=200, verbose_name='dispositivo da contagem'),
        ),
    ]
