# Generated by Django 6.0.5 on 2026-06-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=50, unique=True, verbose_name='código do produto')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('codigo_ean', models.CharField(blank=True, max_length=50, null=True, verbose_name='código EAN')),
                ('setor', models.CharField(max_length=100, verbose_name='setor')),
                ('empresa', models.CharField(max_length=100, verbose_name='empresa')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['codigo_produto'],
            },
        ),
    ]
