# Generated by Django 6.0.5 on 2026-06-10 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usuario_perfil'),
        ('posicoes', '0002_posicao_apto_posicao_data_precadastro_posicao_nivel_and_more'),
        ('produtos', '0003_produto_participa_ciclico'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_precadastro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data do pré-cadastro'),
        ),
        migrations.AddField(
            model_name='produto',
            name='observacao_precadastro',
            field=models.TextField(blank=True, default='', verbose_name='observação do pré-cadastro'),
        ),
        migrations.AddField(
            model_name='produto',
            name='origem_precadastro',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='origem do pré-cadastro'),
        ),
        migrations.AddField(
            model_name='produto',
            name='status_homologacao',
            field=models.CharField(choices=[('HOMOLOGADO', 'Homologado'), ('PENDENTE', 'Pendente de homologação'), ('REJEITADO', 'Rejeitado')], default='HOMOLOGADO', max_length=20, verbose_name='status de homologação'),
        ),
        migrations.AddField(
            model_name='produto',
            name='usuario_precadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_precadastrados', to='accounts.usuario', verbose_name='usuário do pré-cadastro'),
        ),
        migrations.CreateModel(
            name='AuditoriaHomologacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cadastro', models.CharField(choices=[('PRODUTO', 'Produto'), ('POSICAO', 'Posição')], max_length=20, verbose_name='tipo')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='data/hora')),
                ('equipamento', models.CharField(blank=True, default='', max_length=255, verbose_name='equipamento')),
                ('origem', models.CharField(blank=True, default='', max_length=50, verbose_name='origem')),
                ('acao', models.CharField(choices=[('PRECADASTRO', 'Pré-cadastro'), ('APROVACAO', 'Aprovação'), ('EDICAO', 'Edição'), ('REJEICAO', 'Rejeição')], max_length=20, verbose_name='ação')),
                ('status_anterior', models.CharField(blank=True, default='', max_length=20, verbose_name='status anterior')),
                ('status_novo', models.CharField(blank=True, default='', max_length=20, verbose_name='status novo')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='observação')),
                ('dados_alterados', models.JSONField(blank=True, default=dict, verbose_name='dados alterados')),
                ('posicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_homologacao', to='posicoes.posicao')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_homologacao', to='produtos.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_homologacao', to='accounts.usuario', verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'auditoria de homologação',
                'verbose_name_plural': 'auditorias de homologação',
                'ordering': ['-data_hora'],
            },
        ),
    ]
