# Generated by Django 6.0.5 on 2026-06-07 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('posicoes', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='quantidade')),
                ('tipo_movimento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('INVENTARIO', 'Inventário'), ('AJUSTE', 'Ajuste')], max_length=20, verbose_name='tipo de movimento')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('data_movimento', models.DateTimeField(auto_now_add=True, verbose_name='data da movimentação')),
                ('posicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='posicoes.posicao', verbose_name='posição')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='produtos.produto', verbose_name='produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='accounts.usuario', verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'movimentação',
                'verbose_name_plural': 'movimentações',
                'ordering': ['-data_movimento'],
            },
        ),
    ]
