# Generated by Django 6.0.5 on 2026-06-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('OPERADOR', 'Operador'), ('INVENTARIO', 'Operador'), ('CONSULTA', 'Consulta')], max_length=20, verbose_name='perfil'),
        ),
    ]
