# Generated by Django 6.0.5 on 2026-06-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usuario_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('OPERADOR', 'Operador (Pocket)'), ('INVENTARIO', 'Operador de Inventário'), ('CONSULTA', 'Consulta')], max_length=20, verbose_name='perfil'),
        ),
    ]
