# Generated by Django 6.0.5 on 2026-06-07 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueSAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_0', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='canal 0')),
                ('canal_1', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='canal 1')),
                ('canal_2', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='canal 2')),
                ('canal_66', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='canal 66')),
                ('canal_80', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='canal 80')),
                ('canal_81', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='canal 81')),
                ('canal_82', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='canal 82')),
                ('canal_99', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='canal 99')),
                ('canal_110', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='canal 110')),
                ('total', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='total')),
                ('arquivo_origem', models.CharField(max_length=255, verbose_name='arquivo de origem')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='data de importação')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques_sap', to='produtos.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'estoque SAP',
                'verbose_name_plural': 'estoques SAP',
                'ordering': ['-data_importacao'],
            },
        ),
    ]
