# Generated by Django 6.0.5 on 2026-06-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('posicao', models.CharField(max_length=100, verbose_name='posição')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
            ],
            options={
                'verbose_name': 'posição',
                'verbose_name_plural': 'posições',
                'ordering': ['codigo'],
            },
        ),
    ]
