# Generated by Django 6.0.5 on 2026-06-10 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usuario_perfil'),
        ('posicoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicao',
            name='apto',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='apto'),
        ),
        migrations.AddField(
            model_name='posicao',
            name='data_precadastro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data do pré-cadastro'),
        ),
        migrations.AddField(
            model_name='posicao',
            name='nivel',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='nível'),
        ),
        migrations.AddField(
            model_name='posicao',
            name='observacao_precadastro',
            field=models.TextField(blank=True, default='', verbose_name='observação do pré-cadastro'),
        ),
        migrations.AddField(
            model_name='posicao',
            name='origem_precadastro',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='origem do pré-cadastro'),
        ),
        migrations.AddField(
            model_name='posicao',
            name='predio',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='prédio'),
        ),
        migrations.AddField(
            model_name='posicao',
            name='rua',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='rua'),
        ),
        migrations.AddField(
            model_name='posicao',
            name='status_homologacao',
            field=models.CharField(choices=[('HOMOLOGADO', 'Homologado'), ('PENDENTE', 'Pendente de homologação'), ('REJEITADO', 'Rejeitado')], default='HOMOLOGADO', max_length=20, verbose_name='status de homologação'),
        ),
        migrations.AddField(
            model_name='posicao',
            name='usuario_precadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posicoes_precadastradas', to='accounts.usuario', verbose_name='usuário do pré-cadastro'),
        ),
    ]
