# Generated by Django 6.0.5 on 2026-06-07 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posicoes', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='quantidade')),
                ('data_contagem', models.DateTimeField(verbose_name='data da contagem')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('posicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques_fisicos', to='posicoes.posicao', verbose_name='posição')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques_fisicos', to='produtos.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'estoque físico',
                'verbose_name_plural': 'estoques físicos',
                'ordering': ['-data_atualizacao'],
            },
        ),
    ]
