# Generated by Django 6.0.5 on 2026-06-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_fisico', '0001_initial'),
        ('posicoes', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='estoquefisico',
            constraint=models.UniqueConstraint(fields=('produto', 'posicao'), name='uniq_estoquefisico_produto_posicao'),
        ),
    ]
