# Generated by Django 6.0.5 on 2026-06-09 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_fisico', '0002_estoquefisico_uniq_estoquefisico_produto_posicao'),
        ('inventario', '0002_itemciclico_planociclico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquefisico',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data de publicação'),
        ),
        migrations.AddField(
            model_name='estoquefisico',
            name='inventario_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estoques_fisicos_publicados', to='inventario.inventario', verbose_name='inventário de origem'),
        ),
    ]
